version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: makemigrations"
          command: docker-compose run web python manage.py makemigrations
      - run:
          name: "before_test: migrate"
          command: docker-compose run web python manage.py makemigrations
      - run:
          name: test
          command: docker-compose run web python manage.py test tests
      - run:
          name: docker-compose down
          command: docker-compose down

  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: build image
          command: | $(aws ecr get-login --no-include-email --region ap-northeast-1) docker build -t ${ECR_DOMAIN}/sample-image:$CIRCLE_SHA1 -t ${ECR_DOMAIN}/sample-image:latest .


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only:master